#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2016 Tuomas Räsänen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import random
import sys

from PyQt4.QtCore import *
from PyQt4.QtGui import *

class GraphicsGlowEffect(QGraphicsEffect):

    def __init__(self, color):
        super().__init__()

        self.__color  = color
        self.__extent = 100

    def boundingRectFor(self, rect):
        return QRectF(
            rect.left()   - 1 * self.__extent,
            rect.top()    - 1 * self.__extent,
            rect.width()  + 2 * self.__extent,
            rect.height() + 2 * self.__extent)

    def draw(self, painter):
        sourcePixmap, sourceOffset = self.sourcePixmap(Qt.LogicalCoordinates)

        colorizeEffect = QGraphicsColorizeEffect()
        colorizeEffect.setColor(self.__color)

        colorizedPixmap = self.__applyEffectToPixmap(sourcePixmap, colorizeEffect, 0)

        blurEffect = QGraphicsBlurEffect()
        blurEffect.setBlurRadius(15)

        colorizedBlurredPixmap = self.__applyEffectToPixmap(colorizedPixmap,
                                                            blurEffect,
                                                            self.__extent)

        for i in range(5):
            position = sourceOffset - QPoint(self.__extent, self.__extent)
            painter.drawPixmap(position, colorizedBlurredPixmap)
            self.drawSource(painter)

    def __applyEffectToPixmap(self, sourcePixmap, effect, extent):
        if not sourcePixmap:
            return QPixmap()

        if not effect:
            return sourcePixmap

        scene  = QGraphicsScene()
        item   = QGraphicsPixmapItem()
        pixmap = QPixmap(sourcePixmap.width()  + 2 * extent,
                         sourcePixmap.height() + 2 * extent)

        item.setPixmap(sourcePixmap)
        item.setGraphicsEffect(effect)
        scene.addItem(item);
        pixmap.fill(Qt.transparent)
        scene.render(QPainter(pixmap), QRectF(),
                     QRectF(-extent, -extent, pixmap.width(), pixmap.height()))

        return pixmap

class ColorLedButton(QPushButton):

    def __init__(self, color):
        super().__init__()

        self.__color     = color
        colorName        = color.name()
        darkerColorName  = color.darker().name()
        lighterColorName = color.lighter().name()

        self.setStyleSheet("""
ColorLedButton {
 background    : qlineargradient(x1:0, y1:-0.5, x2:0, y2:1.3,
                                 stop:0 %s, stop: 1 %s);
 border-style  : solid;
 border-width  : 1px;
 border-radius : 50px;
 border-color  : black;
 max-width     : 100px;
 max-height    : 100px;
 min-width     : 100px;
 min-height    : 100px;
}

ColorLedButton:pressed {
 background    : qlineargradient(x1:0, y1:0, x2:0, y2:3,
                                 stop:0 %s, stop: 1 %s);
 border-width  : 3px;
 max-width     : 96px;
 max-height    : 96px;
 min-width     : 96px;
 min-height    : 96px;
}

ColorLedButton[isLit="true"] {
 background    : qradialgradient(cx:0.5, cy:0.5, radius:0.8,
                                 fx:0.5, fy:0.5, stop:0 %s, stop: 1 %s);
}

ColorLedButton[isLit="true"]:pressed {
 background    : qradialgradient(cx:0.5, cy:0.5, radius:0.82,
                                 fx:0.55, fy:0.55, stop:0 %s, stop: 1 %s);
}
""" % (lighterColorName, darkerColorName,
       darkerColorName, lighterColorName,
       lighterColorName, colorName,
       lighterColorName, colorName))

        self.setMask(QRegion(QRect(-2, -2, 106, 106), QRegion.Ellipse))
        self.setFocusPolicy(Qt.NoFocus)

    def switchOn(self):
        self.setGraphicsEffect(GraphicsGlowEffect(self.__color))
        self.setProperty("isLit", True)
        self.style().unpolish(self)
        self.style().polish(self)
        self.update()

    def switchOff(self):
        self.setGraphicsEffect(None)
        self.setProperty("isLit", False)
        self.style().unpolish(self)
        self.style().polish(self)
        self.update()

    def isLit(self):
        return self.property("isLit")

class ScoreCounter(QLabel):

    def __init__(self):
        super().__init__("0")

        font = QFont()
        font.setPointSize(48)
        self.setFont(font)
        self.setAlignment(Qt.AlignCenter)

        self.setStyleSheet("""
ScoreCounter {
 background-color : #9f9f9f;
 border-style     : solid;
 border-width     : 1px;
 border-color     : black;
 border-radius    : 10px;
}
        """)

    def increment(self):
        self.setText(str(int(self.text()) + 1))

    def reset(self):
        self.setText("0")

class Dashboard(QWidget):

    def __init__(self):
        super().__init__()

        self.__controller   = Controller()
        self.__scoreCounter = ScoreCounter()

        layout              = QVBoxLayout(self)
        middleRowLayout     = QHBoxLayout()
        bottomRowLayout     = QHBoxLayout()

        redButton           = ColorLedButton(QColor(255, 0, 0))
        greenButton         = ColorLedButton(QColor(0, 255, 0))
        blueButton          = ColorLedButton(QColor(0, 0, 255))
        yellowButton        = ColorLedButton(QColor(255, 255, 0))

        middleRowLayout.addWidget(self.__scoreCounter)

        bottomRowLayout.addStretch()
        bottomRowLayout.addSpacing(50)
        bottomRowLayout.addWidget(redButton)
        bottomRowLayout.addSpacing(50)
        bottomRowLayout.addWidget(greenButton)
        bottomRowLayout.addSpacing(50)
        bottomRowLayout.addWidget(blueButton)
        bottomRowLayout.addSpacing(50)
        bottomRowLayout.addWidget(yellowButton)
        bottomRowLayout.addSpacing(50)
        bottomRowLayout.addStretch()

        layout.addSpacing(50)
        layout.addLayout(middleRowLayout)
        layout.addSpacing(50)
        layout.addLayout(bottomRowLayout)
        layout.addSpacing(50)

        self.__controller.addButton(redButton)
        self.__controller.addButton(greenButton)
        self.__controller.addButton(blueButton)
        self.__controller.addButton(yellowButton)
        self.__controller.setScoreCounter(self.__scoreCounter)

class Controller(QObject):

    def __init__(self):
        super().__init__()

        self.__buttons      = []
        self.__scoreCounter = None
        self.__timerId      = None
        self.__isGameOver   = False

    def timerEvent(self, event):
        for button in self.__buttons:
            if button.isLit():
                button.setText("Too slow!\nGame over!")
                self.__gameOver()
                return

        self.__buttons[random.randrange(len(self.__buttons))].switchOn()

    def __gameOver(self):
        self.killTimer(self.__timerId)
        self.__timerId = None

        self.__isGameOver = True

    def addButton(self, button):
        button.pressed.connect(lambda: self.__buttonPressed(button))
        self.__buttons.append(button)
        button.switchOn()
        button.setText("Press to\nstart!")

    def __buttonPressed(self, button):
        if self.__isGameOver:
            self.__isGameOver = False
            for button in self.__buttons:
                button.switchOn()
                button.setText("Press to\nstart!")
            return

        if self.__timerId is None:
            self.start()
            return

        if not button.isLit():
            button.switchOn()
            button.setText("Wrong button!\nGame over!")
            self.__gameOver()
            return

        button.switchOff()
        self.__scoreCounter.increment()

    def setScoreCounter(self, scoreCounter):
        self.__scoreCounter = scoreCounter

    def start(self):
        for button in self.__buttons:
            button.switchOff()
            button.setText("")
        self.__scoreCounter.reset()
        self.__timerId = self.startTimer(1000)

class MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()

        self.setStyleSheet("background-color: #3f3f3f;")
        self.setCentralWidget(Dashboard())
        self.setWindowTitle("TJJR's Speed Test Game")

def main():
    app = QApplication(sys.argv)

    if app.argc() > 1:
        error_message = "ERROR: invalid number of arguments ({}), expected 0"
        print(error_message.format(app.argc() - 1), file=sys.stderr)
        return 1

    win = MainWindow()
    win.show()

    return app.exec_()

if __name__ == "__main__":
    sys.exit(main())
